### ISSUE TITLE
set up separate JSON files for managing content

### ISSUE THREAD

**Issue by v15hv4** [Amateur-Sports-Enthusiasts-Club/web#5]

**Comment by 5arthak01** [comment]
Can this be assigned to me?

**Comment by v15hv4** [comment]
sure, done

**Comment by 5arthak01** [comment]
Please review commit 1976fdc

**Comment by v15hv4** [comment]
awesome gg
imo it would be more convenient to move the `events/` folder one level up and name it `content/` or something, what do you think?

**Comment by 5arthak01** [comment]
Sure, we can do this. Here's why it is how it is right now - I named it events because that's what it stores, and since these events are used only by the pages, I made it a subdirectory for it. That said, we can go with whatever you decide.

**Comment by v15hv4** [comment]
ahh cool that makes sense, let it just be how it is rn then
